spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}
  datasource:

#    url: ${DATABASE_URL:jdbc:mysql://shinkansen.proxy.rlwy.net:45565/cicd_demo_db}
#    url: ${DATABASE_URL:jdbc:mysql://mysql.railway.internal:3306/cicd_demo_db}
    url: ${DATABASE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration

server:
  port: ${PORT:8080}